modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="the_nine"
version="1.0.0"
displayName="The Nine"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="bug73, MCreator"

[[dependencies.the_nine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




